import pygame
import os

# Screen -settings

POS = WIDTH, HEIGHT = 600 , 800
FPS = 30
SCROLL_SPEED = 8
GRAVITY = 1

# Bird settings
BIRD_START_POS = WIDTH//3,HEIGHT//3
BIRD_ANIMATION_TIME = 150
BIRD_JUMP_VALUE = -16
BIRD_JUMP_ANGLE = 25


# Ground -settings
GROUND_HEIGHT = HEIGHT // 16
GROUND_Y = HEIGHT - GROUND_HEIGHT

# pipe settings
PIPE_HEIGHT = HEIGHT
PIPE_WIDTH = 40
DIST_BTW_PIPES = 350
GAP_HEIGHT = 170
HALF_GAP_HEIGHT = GAP_HEIGHT // 2
